export const SET_CUSTOMERS = '[customer] SET_CUSTOMERS';
export const REMOVE_ADMIN_FROM_CUSTOMERS_LIST =
  '[customer] REMOVE_ADMIN_FROM_CUSTOMERS_LIST';
export const REMOVE_CUSTOMER_FROM_CUSTOMES_LIST =
  '[customer] REMOVE_CUSTOMER_FROM_CUSTOMES_LIST';
